export const Symbols = {
  BrokerIpcTransport: Symbol.for('BrokerIpcTransport'),
  ControllerMetadata: Symbol.for('ControllerMetadata'),
  ControllersMetadataFactory: Symbol.for('ControllersMetadataFactory'),
  ControllerMetadataReader: Symbol.for('ControllerMetadataReader'),
  InternalMiddleware: Symbol.for('InternalMiddleware'),
  GlobalMiddleware: Symbol.for('GlobalMiddleware'),
  MiddlewareFactory: Symbol.for('MiddlewareFactory'),
  MiddlewareExecutorFactory: Symbol.for('MiddlewareExecutorFactory'),
  IpcModuleConfig: Symbol.for('IpcModuleConfig'),
  IpcTransport: Symbol.for('IpcTransport'),
  ModuleMode: Symbol.for('ModuleMode'),
  ExecutionContextFactory: Symbol.for('ExecutionContextFactory'),
  ClientExecutionContextFactory: Symbol.for('ClientExecutionContextFactory'),
  RequestExecutorFactory: Symbol.for('RequestExecutorFactory'),
};
